### ISSUE TITLE
Type AvatarExportedEventPayload hasn't covered the expected parameters

### ISSUE THREAD

**Issue by Folliant** [readyplayerme/rpm-react-avatar-creator#11]
According to the [documentation](https://docs.readyplayer.me/ready-player-me/api-reference/avatar-creator) event `v1.avatar.exported` has three parameters:
```
{
  data: {
    avatarId,
    url,
    userId
  }, 
  eventName: 'v1.avatar.exported',
  source: 'readyplayerme', 
}
```

Execution confirms this statement, however, [type](https://github.com/readyplayerme/rpm-react-avatar-creator/blob/master/src/events/avatar-exported.event.ts) `AvatarExportedEventPayload` has only the `url` key:
```
export type AvatarExportedEventPayload = {
  url: string;
};
```

Could you please verify this behavior?

**Comment by rk132** [comment]
Hey, this package was not updated. This is now done in the package as well. Thanks for noticing it.
